name: news24
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0
  pull_to_refresh: ^2.0.0
  go_router: ^13.0.0
  flutter_riverpod: ^2.0.0
  timeago: ^3.0.2
  share_plus: ^7.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_gen: ^4.2.0
  webdev: ^3.7.2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
assets:
  - assets/images/
  - assets/icons/
# fonts:
#   - family: Prompt
#     fonts:
#       - asset: assets/fonts/Prompt-Regular.ttf
#       - asset: assets/fonts/Prompt-Bold.ttf
#         weight: 700
